[package]
name = "sketches"
version = "0.2.0"
edition = "2024"
autobins = false
description = "Probabilistic data structures for scalable approximate analytics"
license = "MIT"
readme = "README.md"
authors = ["Raja Lehtihet", "Wael El Oraiby"]
repository = "https://github.com/NeoCogi/sketches"
include = [
    "Cargo.toml",
    "Cargo.lock",
    "README.md",
    "CHANGELOG.md",
    "RELEASING.md",
    "LICENSE",
    "src/**",
    "examples/**",
    "benches/**",
    "tests/**",
]

[dependencies]
siphasher = "1.0.3"

[[bench]]
name = "tdigest"
harness = false

[[bench]]
name = "space_saving"
harness = false

[[bench]]
name = "kll"
harness = false

[[bench]]
name = "count_min_sketch"
harness = false

[[bench]]
name = "minhash"
harness = false

[[bench]]
name = "rv_coefficient"
harness = false
