"""Regenerate independent, binary-input LSH model references using only stdlib.

Run: python3 tests/data/generate_lsh_probability_reference.py

The original real-number curve and its algebraic inverse are evaluated with
Decimal at both 900 and 1200 digits. Their independently rounded binary64 outputs
must agree before a vector is written. This does not reproduce the Rust half-
power calculation or its logarithmic correction helper. Tiny forward values
can be discarded only using the union bound b*s**r < one quarter of the smallest
subnormal, well below the rounding midpoint. Setup inputs are encoded as exact
binary64 bits, including neighboring floats around tail transitions.
"""

from decimal import Decimal, localcontext
from pathlib import Path
import math
import random
import struct


CONFIGURATIONS = [
    (1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (3, 2), (4, 2),
    (7, 3), (32, 4), (63, 5), (64, 16), (256, 64), (3, 128),
    (32, 1024), (2, 2048),
]


def bits(value):
    """Encode a binary64 value without decimal-text input rounding."""
    return int.from_bytes(struct.pack(">d", value), "big")


def binary64(encoded):
    """Decode one nonnegative binary64 bit pattern."""
    return struct.unpack(">d", encoded.to_bytes(8, "big"))[0]


def reference(value, bands, rows, direction, precision):
    """Evaluate the ideal curve/inverse from the exact supplied binary float."""
    if value == 0.0 or value == 1.0:
        return bits(value)
    with localcontext() as context:
        context.prec = precision
        one = Decimal(1)
        x = Decimal.from_float(value)
        if direction == "forward":
            match = x ** rows
            if match * bands < Decimal(2) ** -1076:
                return 0
            result = one - (one - match) ** bands
        else:
            match = one - ((one - x).ln() / bands).exp()
            result = (match.ln() / rows).exp()
        return bits(float(result))


def neighboring_inputs(center, radius=3):
    """Select adjacent representable inputs, clipped to the public [0,1] domain."""
    first = max(0, bits(center) - radius)
    last = min(bits(1.0), bits(center) + radius)
    return {binary64(encoded) for encoded in range(first, last + 1)}


def inputs(bands, rows, direction, rng):
    """Mix exact endpoints, subnormals, normal values, and transition neighbors."""
    common = {
        0.0, 1.0, binary64(1), binary64(2), binary64(3), binary64(16),
        binary64(0x000FFFFFFFFFFFFF), binary64(0x0010000000000000),
        binary64(0x0010000000000001), 1e-300, 1e-100, 1e-12,
        0.001, 0.1, 0.25, 0.5, 0.75, 0.9, binary64(bits(1.0) - 1),
    }
    common.update(binary64(rng.randrange(1, bits(1.0))) for _ in range(8))
    if direction == "forward":
        common.update([1e-81, 1.3e-162, 2e-162, 3e-162, 1e-154])
        common.update(neighboring_inputs(math.exp(math.log(float.fromhex("0x1p-1022")) / rows)))
        # Locate final rounding midpoints with high precision, then test the
        # actual binary inputs on both sides rather than assuming a float root
        # lands exactly on that midpoint.
        with localcontext() as context:
            context.prec = 600
            for units in [Decimal("0.5"), Decimal("1.5"), Decimal("15.5")]:
                target = units * Decimal(2) ** -1074 / bands
                center = float((target.ln() / rows).exp())
                common.update(neighboring_inputs(center))
    else:
        common.update(neighboring_inputs(bands * float.fromhex("0x1p-1022")))
        common.update(neighboring_inputs(-math.expm1(-bands)))
    return sorted(common)


def main():
    """Write deterministic references only after both precision runs agree."""
    rng = random.Random(0x4C53485F5441494C)
    output = [
        "# Generated by generate_lsh_probability_reference.py; do not edit.",
        "# Original curve/inverse, exact binary64 inputs, 900/1200 digits agree.",
        "# bands,rows,direction,input_bits,nearest_ideal_output_bits",
    ]
    for bands, rows in CONFIGURATIONS:
        for direction in ["forward", "inverse"]:
            for value in inputs(bands, rows, direction, rng):
                expected = reference(value, bands, rows, direction, 900)
                verified = reference(value, bands, rows, direction, 1200)
                if expected != verified:
                    raise AssertionError((bands, rows, direction, value.hex(), expected, verified))
                output.append(f"{bands},{rows},{direction},{bits(value):016x},{expected:016x}")
    path = Path(__file__).with_name("lsh_probability_reference.csv")
    path.write_text("\n".join(output) + "\n")
    print(f"Wrote {len(output) - 3} independently rounded vectors to {path}")


if __name__ == "__main__":
    main()
